services:
  - type: web
    name: smart-finances-back
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DEBUG
        value: "False"
      - key: JWT_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: BACKEND_CORS_ORIGINS
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "11520"
